/** Generated by the Endaxis game-data compiler. Do not edit. */
import type { WeaponDefinition } from '../../../../core/game-data/equipmentDefinition';
const definition = {
  slug: 'wpn_sword_0017',
  rarity: 6,
  weaponType: 'sword',
  baseAttackAtLevelNodes: [50, 144, 243, 342, 441, 490],
  traits: [
    {
      key: 'skill1',
      levelCount: 9,
      modifiers: [
        {
          kind: 'attribute',
          attribute: 'agility',
          operation: 'flat',
          value: [20, 36, 52, 68, 84, 100, 116, 132, 156],
        },
      ],
      actionGraph: { main: { nodes: {} }, macros: {} },
      skillId: 'wpn_attr_agi_high',
    },
    {
      key: 'skill2',
      levelCount: 9,
      modifiers: [
        {
          kind: 'panelStat',
          stat: 'criticalRate',
          value: [0.025, 0.045, 0.065, 0.085, 0.105, 0.125, 0.145, 0.165, 0.195],
        },
      ],
      actionGraph: { main: { nodes: {} }, macros: {} },
      skillId: 'wpn_sp_attr_crirate_high',
    },
    {
      key: 'skill3',
      levelCount: 9,
      modifiers: [
        {
          kind: 'panelStat',
          stat: 'attackPercent',
          value: [0.07, 0.084, 0.098, 0.112, 0.126, 0.14, 0.154, 0.168, 0.196],
        },
      ],
      actionGraph: {
        main: {
          nodes: {
            createTimedMarker_1: {
              action: {
                kind: 'createTimedMarker',
                parameters: {
                  target: 'caster',
                  markerId: 'wpn_sword_0017',
                  durationSeconds: { kind: 'blackboard', key: 'cd' },
                  autoFinishByAction: false,
                },
              },
              next: null,
            },
            applyBuff_2: {
              action: {
                kind: 'applyBuff',
                parameters: {
                  buffId: 'buff_wpn_sword_0017_exist',
                  target: 'caster',
                  inheritSourceSkillCastInfo: true,
                  asChildBuff: true,
                  copiedBlackboardAssignments: { duration: 'duration', max_stack: 'max_stack' },
                },
              },
              next: 'createTimedMarker_1',
            },
            conditional_3: {
              action: {
                kind: 'conditional',
                parameters: {
                  condition: {
                    kind: 'not',
                    condition: {
                      kind: 'timedMarkerPresent',
                      target: 'caster',
                      markerId: 'wpn_sword_0017',
                    },
                  },
                },
                whenTrue: { $sequence: 'applyBuff_2' },
              },
              next: null,
            },
            conditional_4: {
              action: {
                kind: 'conditional',
                parameters: {
                  condition: {
                    kind: 'originSkillTypeIn',
                    skillTypes: ['battleSkill', 'comboSkill', 'ultimate'],
                  },
                },
                whenTrue: { $sequence: 'conditional_3' },
              },
              next: null,
            },
            conditional_5: {
              action: {
                kind: 'conditional',
                parameters: {
                  condition: {
                    kind: 'eventBuffTagsMatch',
                    match: 'hasAny',
                    buffTags: ['Skill/Character/Common/NoGuard'],
                  },
                },
                whenTrue: { $sequence: 'conditional_4' },
              },
              next: null,
            },
            applyBuff_6: {
              action: {
                kind: 'applyBuff',
                parameters: {
                  buffId: 'buff_wpn_sword_0017_valid',
                  target: 'caster',
                  inheritSourceSkillCastInfo: true,
                  lifetimeOwner: 'currentCastSkill',
                  copiedBlackboardAssignments: { dmg_up: 'dmg_up_final' },
                },
              },
              next: null,
            },
            calculateActionValue_7: {
              action: {
                kind: 'calculateActionValue',
                parameters: {
                  key: 'dmg_up_final',
                  operation: 'multiply',
                  left: { kind: 'blackboard', key: 'dmg_up' },
                  right: { kind: 'blackboard', key: 'count' },
                },
              },
              next: 'applyBuff_6',
            },
            readBuffStackCount_8: {
              action: {
                kind: 'readBuffStackCount',
                parameters: {
                  target: 'caster',
                  outputKey: 'count',
                  query: { kind: 'id', buffIds: ['buff_wpn_sword_0017_exist'] },
                },
              },
              next: 'calculateActionValue_7',
            },
            conditional_9: {
              action: {
                kind: 'conditional',
                parameters: {
                  condition: {
                    kind: 'buffIdStackCompare',
                    target: 'caster',
                    buffIds: ['buff_wpn_sword_0017_exist'],
                    operator: 'greaterOrEqual',
                    value: { kind: 'constant', value: 1 },
                  },
                },
                whenTrue: { $sequence: 'readBuffStackCount_8' },
              },
              next: null,
            },
            conditional_10: {
              action: {
                kind: 'conditional',
                parameters: { condition: { kind: 'eventSkillTypeIn', skillTypes: ['ultimate'] } },
                whenTrue: { $sequence: 'conditional_9' },
              },
              next: null,
            },
          },
        },
        macros: {},
      },
      skillId: 'sk_wpn_sword_0017',
      eventHandlers: [
        {
          key: 'skill3:event:0:sequence:0',
          abilityEvent: 'beforeOutputBuff',
          priority: 0,
          sequence: { $sequence: 'conditional_5' },
        },
        {
          key: 'skill3:event:1:sequence:0',
          abilityEvent: 'beforeCastSkill',
          priority: 0,
          sequence: { $sequence: 'conditional_10' },
        },
      ],
      blackboard: {
        cd: [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
        dmg_up: [0.12, 0.144, 0.168, 0.192, 0.216, 0.24, 0.264, 0.288, 0.336],
        duration: [30, 30, 30, 30, 30, 30, 30, 30, 30],
        max_stack: [3, 3, 3, 3, 3, 3, 3, 3, 3],
      },
    },
  ],
  assetSlug: 'wpn_sword_0017',
  iconPath: '/weapons/sword/wpn_sword_0017.webp',
  buffDefinitions: {
    buff_wpn_sword_0017_exist: {
      stackingType: 'stack',
      priority: 0,
      maxStackCount: { blackboardKey: 'max_stack' },
      durationSeconds: { blackboardKey: 'duration' },
      triggerIntervalSeconds: 0,
      waitFirstTriggerInterval: true,
      maxTriggerCount: 1,
      presentation: {
        visible: true,
        iconId: 'icon_battle_weapon_atk_skill_ready',
        iconPath: '/icons/icon_battle_weapon_atk_skill_ready.webp',
        showInHeadBarCommon: false,
        showInHeadBarAttached: false,
        showInSquadIcon: true,
        onlyShowForMainCharacter: false,
        blinkInMainCharHpBar: false,
        showProgressInHpBar: false,
        showProgressInNormalSkillButton: false,
        useWeakProgressInNormalSkillButton: false,
        showProgressInUltimateSkillButton: false,
        forceRaiseIconEvent: false,
        showWarningBackground: false,
        playStrongInAnimation: false,
        hasCharHpBarVfxType: false,
        charHpBarVfxType: 'Fire',
        iconStyleInSquad: 'LifeTime',
        abnormalColorType: 'Physical',
        orderPriority: { useDirectoryValue: false, value: 0, category: 'CommonCharBuff' },
      },
      applyTags: [],
      extendTags: [],
      blackboard: { duration: 0, max_stack: 0 },
      attributeModifiers: [],
      actionGraph: { main: { nodes: {} }, macros: {} },
    },
    buff_wpn_sword_0017_valid: {
      stackingType: 'unique',
      priority: 0,
      maxStackCount: 0,
      triggerIntervalSeconds: 0,
      waitFirstTriggerInterval: true,
      maxTriggerCount: 1,
      applyTags: [],
      extendTags: [],
      blackboard: { dmg_up: 0 },
      attributeModifiers: [
        {
          attribute: 'physicalDamageIncrease',
          slot: 'baseAddition',
          value: { blackboardKey: 'dmg_up' },
        },
        {
          attribute: 'heatDamageIncrease',
          slot: 'baseAddition',
          value: { blackboardKey: 'dmg_up' },
        },
        {
          attribute: 'electricDamageIncrease',
          slot: 'baseAddition',
          value: { blackboardKey: 'dmg_up' },
        },
        {
          attribute: 'cryoDamageIncrease',
          slot: 'baseAddition',
          value: { blackboardKey: 'dmg_up' },
        },
        {
          attribute: 'natureDamageIncrease',
          slot: 'baseAddition',
          value: { blackboardKey: 'dmg_up' },
        },
      ],
      lifecycleSequences: { finish: { $sequence: 'finishBuffsById_1' } },
      actionGraph: {
        main: {
          nodes: {
            finishBuffsById_1: {
              action: {
                kind: 'finishBuffsById',
                parameters: {
                  target: 'caster',
                  buffIds: ['buff_wpn_sword_0017_exist'],
                  reason: 'other',
                },
              },
              next: null,
            },
          },
        },
        macros: {},
      },
    },
  },
} as const satisfies WeaponDefinition;
export default definition;
