/** Generated by the Endaxis game-data compiler. Do not edit. */
import type { GearSetDefinition } from '../../../core/game-data/equipmentDefinition';

const definition = {
  slug: 'suit_atk02',
  iconPath: '/equipment/atk02/item_equip_t4_suit_atk02_edc_04.webp',
  modifiers: [{ kind: 'panelStat', stat: 'attackPercent', value: 0.15 }],
  skillId: 'passive_equipsuit_atk_02',
  buffDefinitions: {
    buff_equipsuit_atk_02: {
      stackingType: 'unlimited',
      priority: 0,
      maxStackCount: 0,
      triggerIntervalSeconds: 0,
      waitFirstTriggerInterval: true,
      maxTriggerCount: 1,
      applyTags: [],
      extendTags: [],
      blackboard: { atk_up: 0.1, dmg_up: 0.2, max_stack: 5 },
      attributeModifiers: [],
      lifecycleSequences: { enable: { $sequence: 'applyBuff_1' } },
      actionGraph: {
        main: {
          nodes: {
            applyBuff_1: {
              action: {
                kind: 'applyBuff',
                parameters: {
                  buffId: 'buff_equipsuit_atk_02_aruadetect',
                  target: 'party',
                  source: 'buffOwner',
                  finishByAction: true,
                  blackboardAssignments: {
                    dmg_up: { kind: 'blackboard', key: 'dmg_up' },
                    max_stack: { kind: 'blackboard', key: 'max_stack' },
                  },
                },
              },
              next: null,
            },
          },
        },
        macros: {},
      },
    },
    buff_equipsuit_atk_02_addcombodamage: {
      stackingType: 'stack',
      priority: 0,
      maxStackCount: { blackboardKey: 'max_stack' },
      triggerIntervalSeconds: 0,
      waitFirstTriggerInterval: true,
      maxTriggerCount: 1,
      presentation: {
        visible: true,
        iconId: 'icon_battle_buff_atk_up',
        iconPath: '/icons/icon_battle_buff_atk_up.webp',
        showInHeadBarCommon: false,
        showInHeadBarAttached: false,
        showInSquadIcon: true,
        onlyShowForMainCharacter: false,
        blinkInMainCharHpBar: false,
        showProgressInHpBar: false,
        showProgressInNormalSkillButton: false,
        useWeakProgressInNormalSkillButton: false,
        showProgressInUltimateSkillButton: false,
        forceRaiseIconEvent: false,
        showWarningBackground: false,
        playStrongInAnimation: false,
        hasCharHpBarVfxType: false,
        charHpBarVfxType: 'Fire',
        iconStyleInSquad: 'Default',
        abnormalColorType: 'Physical',
        orderPriority: { useDirectoryValue: false, value: 0, category: 'CommonCharBuff' },
      },
      applyTags: [],
      extendTags: [],
      blackboard: { atk_up: 0.1, dmg_up: 0.2, max_stack: 5, stack: 5 },
      attributeModifiers: [],
      abilityEventResponses: [
        { event: 'beforeCastSkill', priority: 0, sequence: { $sequence: 'conditional_5' } },
      ],
      actionGraph: {
        main: {
          nodes: {
            finishBuffsById_1: {
              action: {
                kind: 'finishBuffsById',
                parameters: {
                  target: 'buffOwner',
                  buffIds: ['buff_equipsuit_atk_02_addcombodamage'],
                  reason: 'other',
                },
              },
              next: null,
            },
            applyBuff_2: {
              action: {
                kind: 'applyBuff',
                parameters: {
                  buffId: 'buff_equipsuit_atk_02_addcombodamage_buff',
                  target: 'buffOwner',
                  source: 'buffOwner',
                  inheritSourceSkillCastInfo: true,
                  copiedBlackboardAssignments: { dmg_up: 'dmg_up' },
                },
              },
              next: 'finishBuffsById_1',
            },
            modifyActionValue_3: {
              action: {
                kind: 'modifyActionValue',
                parameters: {
                  key: 'dmg_up',
                  operation: 'multiply',
                  value: { kind: 'blackboard', key: 'stack' },
                },
              },
              next: 'applyBuff_2',
            },
            readBuffStackCount_4: {
              action: {
                kind: 'readBuffStackCount',
                parameters: {
                  target: 'buffOwner',
                  outputKey: 'stack',
                  query: { kind: 'id', buffIds: ['buff_equipsuit_atk_02_addcombodamage'] },
                },
              },
              next: 'modifyActionValue_3',
            },
            conditional_5: {
              action: {
                kind: 'conditional',
                parameters: { condition: { kind: 'eventSkillTypeIn', skillTypes: ['comboSkill'] } },
                whenTrue: { $sequence: 'readBuffStackCount_4' },
              },
              next: null,
            },
          },
        },
        macros: {},
      },
    },
    buff_equipsuit_atk_02_addcombodamage_buff: {
      stackingType: 'unique',
      priority: 0,
      maxStackCount: 5,
      triggerIntervalSeconds: 0,
      waitFirstTriggerInterval: true,
      maxTriggerCount: 1,
      applyTags: [],
      extendTags: [],
      blackboard: { dmg_up: 0.2 },
      attributeModifiers: [],
      damageModifiers: [
        {
          enabledSide: 'attacker',
          condition: {
            kind: 'all',
            conditions: [
              { kind: 'sourceSkillCastMatch' },
              { kind: 'eventDamageTagsMatch', match: 'hasAll', tags: ['comboSkill'] },
            ],
          },
          processors: [
            {
              kind: 'damageScale',
              side: 'attacker',
              zone: 'normal',
              addition: { blackboardKey: 'dmg_up' },
            },
          ],
        },
      ],
      lifecycleSequences: { enable: { $sequence: 'skillAffix_1' } },
      actionGraph: {
        main: {
          nodes: { skillAffix_1: { action: { kind: 'skillAffix', parameters: {} }, next: null } },
        },
        macros: {},
      },
    },
    buff_equipsuit_atk_02_aruadetect: {
      stackingType: 'unlimited',
      priority: 0,
      maxStackCount: 0,
      triggerIntervalSeconds: 0,
      waitFirstTriggerInterval: true,
      maxTriggerCount: 1,
      applyTags: [],
      extendTags: [],
      blackboard: { atk_up: 0.1, dmg_up: 0.2, max_stack: 5 },
      attributeModifiers: [],
      abilityEventResponses: [
        { event: 'beforeCastSkill', priority: 0, sequence: { $sequence: 'conditional_2' } },
      ],
      actionGraph: {
        main: {
          nodes: {
            applyBuff_1: {
              action: {
                kind: 'applyBuff',
                parameters: {
                  buffId: 'buff_equipsuit_atk_02_addcombodamage',
                  target: 'caster',
                  inheritSourceSkillCastInfo: true,
                  asChildBuff: true,
                  copiedBlackboardAssignments: { dmg_up: 'dmg_up', max_stack: 'max_stack' },
                },
              },
              next: null,
            },
            conditional_2: {
              action: {
                kind: 'conditional',
                parameters: {
                  condition: { kind: 'eventSkillTypeIn', skillTypes: ['battleSkill'] },
                },
                whenTrue: { $sequence: 'applyBuff_1' },
              },
              next: null,
            },
          },
        },
        macros: {},
      },
    },
  },
  enableSequence: { $sequence: 'applyBuff_1' },
  actionGraph: {
    main: {
      nodes: {
        applyBuff_1: {
          action: {
            kind: 'applyBuff',
            parameters: {
              buffId: 'buff_equipsuit_atk_02',
              target: 'caster',
              blackboardAssignments: {
                atk_up: { kind: 'constant', value: 0.15 },
                dmg_up: { kind: 'constant', value: 0.2 },
                max_stack: { kind: 'constant', value: 3 },
              },
            },
          },
          next: null,
        },
      },
    },
    macros: {},
  },
} as const satisfies GearSetDefinition;

export default definition;
