/** Generated by the Endaxis game-data compiler. Do not edit. */
import type { WeaponDefinition } from '../../../../core/game-data/equipmentDefinition';
const definition = {
  slug: 'wpn_pistol_0004',
  rarity: 5,
  weaponType: 'handcannon',
  baseAttackAtLevelNodes: [42, 120, 203, 286, 369, 411],
  traits: [
    {
      key: 'skill1',
      levelCount: 9,
      modifiers: [
        {
          kind: 'attribute',
          attribute: 'strength',
          operation: 'flat',
          value: [16, 28, 41, 54, 67, 80, 92, 105, 124],
        },
      ],
      actionGraph: { main: { nodes: {} }, macros: {} },
      skillId: 'wpn_attr_str_mid',
    },
    {
      key: 'skill2',
      levelCount: 9,
      modifiers: [
        {
          kind: 'damageScale',
          target: 'heat',
          slot: 'baseAddition',
          value: [
            0.044444446, 0.08, 0.115555555, 0.15111111, 0.18666667, 0.22222222, 0.25777778,
            0.29333332, 0.34666666,
          ],
        },
      ],
      actionGraph: { main: { nodes: {} }, macros: {} },
      skillId: 'wpn_sp_attr_firedam_mid',
    },
    {
      key: 'skill3',
      levelCount: 9,
      modifiers: [
        {
          kind: 'damageScale',
          target: 'battleSkill',
          slot: 'baseAddition',
          value: [0.1, 0.12, 0.14, 0.16, 0.18, 0.2, 0.22, 0.24, 0.28],
        },
      ],
      skillId: 'sk_wpn_pistol_0004',
      eventHandlers: [
        {
          key: 'skill3:event:0:sequence:0',
          abilityEvent: 'beforeOutputSpellBurst',
          priority: 0,
          sequence: { $sequence: 'conditional_2' },
        },
        {
          key: 'skill3:event:1:sequence:0',
          abilityEvent: 'beforeOutputBuff',
          priority: 0,
          sequence: { $sequence: 'conditional_5' },
        },
      ],
      actionGraph: {
        main: {
          nodes: {
            applyBuff_1: {
              action: {
                kind: 'applyBuff',
                parameters: {
                  buffId: 'buff_wpn_pistol_0004_atk_up',
                  target: 'caster',
                  inheritSourceSkillCastInfo: true,
                  asChildBuff: true,
                  copiedBlackboardAssignments: { atk_up: 'atk_up', duration: 'duration' },
                },
              },
              next: null,
            },
            conditional_2: {
              action: {
                kind: 'conditional',
                parameters: {
                  condition: { kind: 'originSkillTypeIn', skillTypes: ['comboSkill'] },
                },
                whenTrue: { $sequence: 'applyBuff_1' },
              },
              next: null,
            },
            conditional_4: {
              action: {
                kind: 'conditional',
                parameters: {
                  condition: {
                    kind: 'eventBuffTagsMatch',
                    match: 'hasAny',
                    buffTags: ['Skill/Character/Common/SpellStatus/Burning'],
                  },
                },
                whenTrue: { $sequence: 'applyBuff_1' },
              },
              next: null,
            },
            conditional_5: {
              action: {
                kind: 'conditional',
                parameters: {
                  condition: { kind: 'originSkillTypeIn', skillTypes: ['comboSkill'] },
                },
                whenTrue: { $sequence: 'conditional_4' },
              },
              next: null,
            },
          },
        },
        macros: {},
      },
      blackboard: {
        atk_up: [0.16, 0.192, 0.224, 0.256, 0.288, 0.32, 0.352, 0.384, 0.448],
        duration: [15, 15, 15, 15, 15, 15, 15, 15, 15],
      },
    },
  ],
  assetSlug: 'wpn_handcannon_0004',
  iconPath: '/weapons/handcannon/wpn_handcannon_0004.webp',
  buffDefinitions: {
    buff_wpn_pistol_0004_atk_up: {
      stackingType: 'stack',
      priority: 0,
      maxStackCount: 1,
      durationSeconds: { blackboardKey: 'duration' },
      triggerIntervalSeconds: 0,
      waitFirstTriggerInterval: true,
      maxTriggerCount: 1,
      presentation: {
        visible: true,
        iconId: 'icon_battle_buff_atk_up',
        iconPath: '/icons/icon_battle_buff_atk_up.webp',
        showInHeadBarCommon: false,
        showInHeadBarAttached: false,
        showInSquadIcon: true,
        onlyShowForMainCharacter: false,
        blinkInMainCharHpBar: false,
        showProgressInHpBar: false,
        showProgressInNormalSkillButton: false,
        useWeakProgressInNormalSkillButton: false,
        showProgressInUltimateSkillButton: false,
        forceRaiseIconEvent: false,
        showWarningBackground: false,
        playStrongInAnimation: false,
        hasCharHpBarVfxType: false,
        charHpBarVfxType: 'Fire',
        iconStyleInSquad: 'LifeTime',
        abnormalColorType: 'Physical',
        orderPriority: { useDirectoryValue: false, value: 0, category: 'CommonCharBuff' },
      },
      applyTags: [],
      extendTags: [],
      blackboard: { atk_up: 0, duration: 0 },
      attributeModifiers: [
        { attribute: 'Atk', slot: 'baseMultiplier', value: { blackboardKey: 'atk_up' } },
      ],
      actionGraph: { main: { nodes: {} }, macros: {} },
    },
  },
} as const satisfies WeaponDefinition;
export default definition;
