/** Generated by the Endaxis game-data compiler. Do not edit. */
import type { WeaponDefinition } from '../../../../core/game-data/equipmentDefinition';
const definition = {
  slug: 'wpn_funnel_0006',
  rarity: 6,
  weaponType: 'arts-unit',
  baseAttackAtLevelNodes: [49, 142, 240, 338, 436, 485],
  traits: [
    {
      key: 'skill1',
      levelCount: 9,
      modifiers: [
        {
          kind: 'attribute',
          attribute: 'will',
          operation: 'flat',
          value: [20, 36, 52, 68, 84, 100, 116, 132, 156],
        },
      ],
      actionGraph: { main: { nodes: {} }, macros: {} },
      skillId: 'wpn_attr_will_high',
    },
    {
      key: 'skill2',
      levelCount: 9,
      modifiers: [
        {
          kind: 'damageScale',
          target: 'nature',
          slot: 'baseAddition',
          value: [
            0.055555556, 0.1, 0.14444445, 0.18888889, 0.23333333, 0.2777778, 0.32222223, 0.36666667,
            0.43333334,
          ],
        },
      ],
      actionGraph: { main: { nodes: {} }, macros: {} },
      skillId: 'wpn_sp_attr_naturaldam_high',
    },
    {
      key: 'skill3',
      levelCount: 9,
      modifiers: [
        {
          kind: 'panelStat',
          stat: 'attackPercent',
          value: [0.07, 0.084, 0.098, 0.112, 0.126, 0.14, 0.154, 0.168, 0.196],
        },
      ],
      actionGraph: {
        main: {
          nodes: {
            applyBuff_1: {
              action: {
                kind: 'applyBuff',
                parameters: {
                  buffId: 'buff_wpn_funnel_0006',
                  target: 'caster',
                  inheritSourceSkillCastInfo: true,
                  asChildBuff: true,
                  copiedBlackboardAssignments: {
                    spell_dmg_up: 'spell_dmg_up',
                    duration: 'duration',
                    max_stack: 'max_stack',
                    spell_dmg_up2: 'spell_dmg_up2',
                  },
                },
              },
              next: null,
            },
            conditional_2: {
              action: {
                kind: 'conditional',
                parameters: {
                  condition: { kind: 'eventSkillTypeIn', skillTypes: ['battleSkill'] },
                },
                whenTrue: { $sequence: 'applyBuff_1' },
              },
              next: null,
            },
          },
        },
        macros: {},
      },
      skillId: 'sk_wpn_funnel_0006',
      eventHandlers: [
        {
          key: 'skill3:event:0:sequence:0',
          abilityEvent: 'beforeCastSkill',
          priority: 0,
          sequence: { $sequence: 'conditional_2' },
        },
      ],
      blackboard: {
        duration: [15, 15, 15, 15, 15, 15, 15, 15, 15],
        max_stack: [3, 3, 3, 3, 3, 3, 3, 3, 3],
        spell_dmg_up: [0.05, 0.06, 0.07, 0.08, 0.09, 0.1, 0.11, 0.12, 0.14],
        spell_dmg_up2: [0.02, 0.024, 0.028, 0.032, 0.036, 0.04, 0.044, 0.048, 0.056],
      },
    },
  ],
  assetSlug: 'wpn_artsunit_0006',
  iconPath: '/weapons/arts-unit/wpn_artsunit_0006.webp',
  buffDefinitions: {
    buff_wpn_funnel_0006: {
      stackingType: 'unlimited',
      priority: 0,
      maxStackCount: 0,
      triggerIntervalSeconds: 0,
      waitFirstTriggerInterval: true,
      maxTriggerCount: 1,
      applyTags: [],
      extendTags: [],
      blackboard: {
        count: 0,
        duration: 15,
        lv: 0,
        max_stack: 3,
        spell_dmg_up: 0.05,
        spell_dmg_up_final: 0,
        spell_dmg_up2: 0.01,
      },
      attributeModifiers: [],
      lifecycleSequences: {
        start: { $sequence: 'mergeContextTargets_1' },
        enable: { $sequence: 'skillAffix_2' },
      },
      abilityEventResponses: [
        { event: 'beforeOutputInfliction', priority: 0, sequence: { $sequence: 'conditional_12' } },
      ],
      actionGraph: {
        main: {
          nodes: {
            mergeContextTargets_1: {
              action: {
                kind: 'mergeContextTargets',
                parameters: { saveToContextKey: 'wpn_funnel_0006_total_tar', sources: [] },
              },
              next: null,
            },
            skillAffix_2: { action: { kind: 'skillAffix', parameters: {} }, next: null },
            applyBuff_3: {
              action: {
                kind: 'applyBuff',
                parameters: {
                  buffId: 'buff_wpn_funnel_0006_valid',
                  target: 'partyExceptCaster',
                  inheritSourceSkillCastInfo: true,
                  copiedBlackboardAssignments: {
                    spell_dmg_up: 'spell_dmg_up_final',
                    duration: 'duration',
                  },
                },
              },
              next: null,
            },
            modifyActionValue_4: {
              action: {
                kind: 'modifyActionValue',
                parameters: {
                  key: 'spell_dmg_up_final',
                  operation: 'add',
                  value: { kind: 'blackboard', key: 'spell_dmg_up' },
                },
              },
              next: 'applyBuff_3',
            },
            calculateActionValue_5: {
              action: {
                kind: 'calculateActionValue',
                parameters: {
                  key: 'spell_dmg_up_final',
                  operation: 'multiply',
                  left: { kind: 'blackboard', key: 'count' },
                  right: { kind: 'blackboard', key: 'spell_dmg_up2' },
                },
              },
              next: 'modifyActionValue_4',
            },
            conditional_6: {
              action: {
                kind: 'conditional',
                parameters: {
                  condition: {
                    kind: 'actionValueCompare',
                    left: { kind: 'blackboard', key: 'count', fallback: 0 },
                    operator: 'lessOrEqual',
                    right: { kind: 'blackboard', key: 'max_stack', fallback: 0 },
                  },
                },
                whenTrue: { $sequence: 'calculateActionValue_5' },
              },
              next: null,
            },
            conditional_7: {
              action: {
                kind: 'conditional',
                parameters: {
                  condition: {
                    kind: 'contextTargetCountCompare',
                    contextKey: 'wpn_funnel_0006_total_tar',
                    operator: 'greaterOrEqual',
                    value: 1,
                    outputKey: 'count',
                  },
                },
                whenTrue: { $sequence: 'conditional_6' },
              },
              next: null,
            },
            mergeContextTargets_8: {
              action: {
                kind: 'mergeContextTargets',
                parameters: {
                  saveToContextKey: 'wpn_funnel_0006_total_tar',
                  sources: [
                    { kind: 'target', target: 'eventTarget' },
                    { kind: 'context', contextKey: 'wpn_funnel_0006_total_tar' },
                  ],
                },
              },
              next: 'conditional_7',
            },
            conditional_9: {
              action: {
                kind: 'conditional',
                parameters: {
                  condition: {
                    kind: 'not',
                    condition: {
                      kind: 'contextTargetContains',
                      parentContextKey: 'wpn_funnel_0006_total_tar',
                      child: 'eventTarget',
                    },
                  },
                },
                whenTrue: { $sequence: 'mergeContextTargets_8' },
              },
              next: null,
            },
            conditional_10: {
              action: {
                kind: 'conditional',
                parameters: {
                  condition: { kind: 'originSkillTypeIn', skillTypes: ['battleSkill'] },
                },
                whenTrue: { $sequence: 'conditional_9' },
              },
              next: null,
            },
            conditional_11: {
              action: {
                kind: 'conditional',
                parameters: { condition: { kind: 'eventSkillCastMatchesBuffSource' } },
                whenTrue: { $sequence: 'conditional_10' },
              },
              next: null,
            },
            conditional_12: {
              action: {
                kind: 'conditional',
                parameters: {
                  condition: { kind: 'eventInflictionElementIn', elements: ['nature'] },
                },
                whenTrue: { $sequence: 'conditional_11' },
              },
              next: null,
            },
          },
        },
        macros: {},
      },
    },
    buff_wpn_funnel_0006_valid: {
      stackingType: 'highPriority',
      priority: { blackboardKey: 'spell_dmg_up' },
      maxStackCount: 1,
      durationSeconds: { blackboardKey: 'duration' },
      triggerIntervalSeconds: 0,
      waitFirstTriggerInterval: true,
      maxTriggerCount: 1,
      presentation: {
        visible: true,
        iconId: 'icon_battle_spell_up',
        iconPath: '/icons/icon_battle_spell_up.webp',
        showInHeadBarCommon: false,
        showInHeadBarAttached: false,
        showInSquadIcon: true,
        onlyShowForMainCharacter: false,
        blinkInMainCharHpBar: false,
        showProgressInHpBar: false,
        showProgressInNormalSkillButton: false,
        useWeakProgressInNormalSkillButton: false,
        showProgressInUltimateSkillButton: false,
        forceRaiseIconEvent: false,
        showWarningBackground: false,
        playStrongInAnimation: false,
        hasCharHpBarVfxType: false,
        charHpBarVfxType: 'Fire',
        iconStyleInSquad: 'LifeTime',
        abnormalColorType: 'Physical',
        orderPriority: { useDirectoryValue: false, value: 0, category: 'CommonCharBuff' },
      },
      applyTags: [],
      extendTags: [],
      blackboard: { duration: 15, spell_dmg_up: 0.05 },
      attributeModifiers: [
        {
          attribute: 'heatDamageIncrease',
          slot: 'baseAddition',
          value: { blackboardKey: 'spell_dmg_up' },
        },
        {
          attribute: 'electricDamageIncrease',
          slot: 'baseAddition',
          value: { blackboardKey: 'spell_dmg_up' },
        },
        {
          attribute: 'cryoDamageIncrease',
          slot: 'baseAddition',
          value: { blackboardKey: 'spell_dmg_up' },
        },
        {
          attribute: 'natureDamageIncrease',
          slot: 'baseAddition',
          value: { blackboardKey: 'spell_dmg_up' },
        },
      ],
      actionGraph: { main: { nodes: {} }, macros: {} },
    },
  },
} as const satisfies WeaponDefinition;
export default definition;
